In [1]:
a = [34,23,12,88,95,74]

In [2]:
29 in a

False

In [3]:
 5>3

True

In [4]:
import numpy as np
import pandas as pd

In [6]:
grades = np.array([80,85,90])
percentage = np.array([0.35,0.4,0.25])
np.dot(grades, percentage)

84.5

In [7]:
# np.linspace(0:start number, 10:last number, 6: how many numbers to generate)
np.linspace(0,10,6)

array([ 0.,  2.,  4.,  6.,  8., 10.])

In [9]:
# list(range(0:start number, 10:last number, 2:interval))
list(range(0,10,2))

[0, 2, 4, 6, 8]

In [12]:
x = np.array([[1,2],[3,4]])

In [13]:
x.ndim

2

In [14]:
x.shape

(2, 2)

In [15]:
x.reshape(1,4)

array([[1, 2, 3, 4]])

In [17]:
x

array([[1, 2],
       [3, 4]])

In [16]:
x.sum(axis=0)

array([4, 6])

In [18]:
x.sum(axis=1)

array([3, 7])

In [25]:
a = list(range(1,16,1))

In [26]:
a = np.array([a])

In [29]:
a.reshape(3,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])